### PR TITLE
Add a configurator web page & generate prettier rules

### PR DESCRIPTION
**Pull request by swansontec**
This branch adds a [configuration web page](https://www.swansontec.com/eslint-config-standard-kit), to make it easier to set up the library.

It also deprecates the `lint/` configs and replaces them with `prettier/` configs, since that's the main reason these variants exist, so there's no point having the user do extra work.

### CODE REVIEW

**Comment by swansontec** [comment]
@feross, @mightyiam, I would love your feedback on the configurator web page.

My goal is to make Standard.js easy to combine with other tools like TypeScript, Flow, or Prettier. I think this is a step in the right direction.

**Comment by mightyiam** [comment]
@swansontec, thank you for this work. I like the page. I feel (I you surely know) that most if not all of the issues that this project aims to solve can and should be solved in Standard itself. And I would love for you to contribute there to help that happen.

**Comment by swansontec** [comment]
@mightyiam I agree. If you check all the "language features" boxes, you do actually get support for Node, JSX, Typescript, & Flow in a single config. The fact that your library puts Typescript support inside an `overrides` block is the key to making this possible - without it, Flow & Typescript would fight. Since we can have our cake & eat it too, there is no real downside to having the official Standard.js CLI from just supporting these language variants out of the box. I would love to help make this happen.

At the same time, standard-kit does some "out of scope" use cases like replacing the Standard.js formatting rules with Prettier. There may still be a place for a tool like standard-kit, even in a world where Standard.js pulls in a lot of this functionality.

**Comment by mightyiam** [comment]
Speaking of which, do you like [my suggestion to make Standard extensible](https://github.com/standard/standard/pull/703)?

**Pull request merged**
